/*
MINI SISTEMA DE FACTURACION
CLIENTE: CODIGO, NOMBRE, NIT, TELEFONO, DIRECCION
PRODUCTO: CODIGO, NOMBRE
FACTURA: CODIGO, CODIGO_CLIENTE, FECHA
DETALLE_FACTURA: CODIGO_FACTURA, CANTIDAD, PRECIO_UNITARIO, COD_PRODUCTO

LLENAR DATOS DE https://www.mockaroo.com/ CSV
CLIENTES:500
PRODUCTOS: 1000
FACTURA: 200 EN UN RANGO DE FECHAS DE 1 MES
DETALLE: 1000
*/

--CREATE DATABASE MINI_SUPER
--GO

USE MINI_SUPER
GO

CREATE TABLE CLIENTE(
COD_CLIENTE INT,
NOMBRE VARCHAR(100),
NIT VARCHAR(8),
TELEFONO VARCHAR(8),
DIRECCION VARCHAR(100),
CONSTRAINT PK_CLIENTE PRIMARY KEY(COD_CLIENTE)
)

CREATE TABLE PRODUCTO(
COD_PRODUCTO INT,
NOMBRE VARCHAR(100)
CONSTRAINT PK_PRODUCTO PRIMARY KEY(COD_PRODUCTO)
)

CREATE TABLE FACTURA (
COD_FACTURA INT, 
COD_CLIENTE INT, 
FECHA DATE,
CONSTRAINT PK_FACTURA PRIMARY KEY(COD_FACTURA),
CONSTRAINT FK_FACTURA_CLIENTE FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)
)

CREATE TABLE DETALLE_FACTURA(
COD_FACTURA INT, 
CANTIDAD INT, 
PRECIO_UNITARIO NUMERIC(16,2), 
COD_PRODUCTO INT,
CONSTRAINT FK_DETALLE_FACTURA FOREIGN KEY(COD_FACTURA) REFERENCES FACTURA(COD_FACTURA),
CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY(COD_PRODUCTO) REFERENCES PRODUCTO(COD_PRODUCTO)
)
SELECT * FROM CLIENTE
SELECT * FROM PRODUCTO
SELECT * FROM FACTURA
SELECT * FROM DETALLE_FACTURA